### ISSUE TITLE
Trouble getting this skeleton to render index.static.jade

### ISSUE THREAD

**Issue by ajfiorani** [glitterwitch/brunch-jade-stylus#3]
I cannot seem to get this to build `index.static.jade`. All that it will build is  `/app/assets/index.html` even if I delete that index.html file it will not render the .jade file. how do I get it to build the jade file?

Also is there anywhere I can find documentation on how to use this skeleton?

**Comment by KATT** [comment]
It renders the `.jade` file into `.html` - what is the problem?
